export default [
  { type: 'horizon', id: 2, },
  { type: 'haze', id: 4, },
  { type: 'roadname_marker', id: 199, size: 10 },
  { type: 'roadname_marker', id: 200, size: 30 },
  { type: 'roadname_marker_shadow_2d', id: 198, size: 10 },
  { type: 'roadname_marker_shadow_3d', id: 197, size: 10 },
  { type: 'roadname_marker_shadow_2d', id: 201, size: 30 },
  { type: 'roadname_marker_shadow_3d', id: 202, size: 30 },
  { type: 'horizon_marker', id: 0, },
  { type: 'tunnel_marker', id: 0, },
  { type: 'oneway_pattern', id: 0, },
  { type: 'railway_pattern', id: 0, },
  { type: 'ferry_pattern', id: 0, },
  { type: 'restricted_road_pattern', id: 0, },
  { type: 'frame_around_map_top_left', id: 20200, },
  { type: 'frame_around_map_top_right', id: 20201, },
  { type: 'frame_around_map_bottom_left', id: 20202, },
  { type: 'frame_around_map_bottom_right', id: 20203, }
];