export default [
  { name: 'countryroad', outline: { colour: '#374b64', style: 'transparent' }, fill: { colour: '#2e3340', style: 'solid' } } /* Debug red */ ,
  { name: 'countryroad_bridge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'countryroad_hov_lane', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'countryroad_seasonally_restricted', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'countryroad_special_charge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'countryroad_toll', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'countryroad_tunnel', outline: { colour: '#374b64', style: 'transparent' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'dualcarriageway', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } } /* Debug green */,
  { name: 'dualcarriageway_bridge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'dualcarriageway_hov_lane', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'dualcarriageway_seasonally_restricted', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'dualcarriageway_special_charge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'dualcarriageway_toll', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'dualcarriageway_tunnel', outline: { colour: '#374b64', style: 'transparent' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'expressway', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } }, /* Debug  blue */
  { name: 'expressway_bridge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'expressway_hov_lane', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'expressway_seasonally_restricted', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'expressway_special_charge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'expressway_toll', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'expressway_tunnel', outline: { colour: '#374b64', style: 'transparent' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'motorway', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'motorway_bridge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'motorway_exit_marker', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'motorway_hov_lane', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'motorway_seasonally_restricted', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'motorway_special_charge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'motorway_toll', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'motorway_tunnel', outline: { colour: '#374b64', style: 'transparent' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'restricted_road', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'urbanroad', outline: { colour: '#374b64', style: 'transparent' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'urbanroad_bridge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'urbanroad_hov_lane', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'urbanroad_seasonally_restricted', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'urbanroad_special_charge', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'urbanroad_toll', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'urbanroad_tunnel', outline: { colour: '#374b64', style: 'transparent' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'footway', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'hiking_trail_bike', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'hiking_trail_fixed_rope', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
  { name: 'hiking_trail_main', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'transparent' } },
  { name: 'one_way_street', outline: { colour: '#374b64', style: 'solid' }, fill: { colour: '#2e3340', style: 'solid' } },
];